name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: instpackages
      run: sudo apt-get install libncurses5-dev libncursesw5-dev libsdl2-2.0-0 libsdl2-ttf-2.0-0 
    - name: make
      run: make
